name: Plugin CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Parse extension
        run: | 
          cd action/extension
          npm install -g typescript
          npm install
          tsc
          node src/extension_parse.js

      - name: Commit files
        run: |
          pwd
          ls
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - uses: actions/checkout@v4
        with:
          ref: public
          path: public

      - name: Commit
        run: |
          cd public
          mkdir -p repository
          git rm -r repository
          mv ../repository . -f
          git add .
          git commit -m "[auto] extension parse"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.token }}
          branch: public